/*
SET FOREIGN_KEY_CHECKS = 0

SELECT concat('DROP TABLE IF EXISTS `', table_name, '`;')
FROM information_schema.tables
WHERE table_schema = 'heroku_512342ab1505158';

SET FOREIGN_KEY_CHECKS = 1
*/

DROP TABLE IF EXISTS JuegoCompartido;
DROP TABLE IF EXISTS CopiaJuego;
DROP TABLE IF EXISTS Sesion;
DROP TABLE IF EXISTS UsuarioEliminado;
DROP TABLE IF EXISTS Administrador;
DROP TABLE IF EXISTS Compartido;
DROP TABLE IF EXISTS Tiene;
DROP TABLE IF EXISTS Amigos;
DROP TABLE IF EXISTS Partida;
DROP TABLE IF EXISTS Juego;
DROP TABLE IF EXISTS Usuario;
